{{ if .Values.isOCP }}
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
{{ else }}
apiVersion: apps/v1
kind: Deployment
{{ end }}
metadata:
  labels:
    application: {{ .Release.Name }}
    version: {{ .Values.version }}
  name: {{ .Release.Name }}-{{ .Values.version }}
spec:
  replicas: 1
  selector:
    matchLabels:
      deploymentConfig: {{ .Release.Name }}-{{ .Values.version }} 
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        application: {{ .Release.Name }}
        version: {{ .Values.version }}
        deploymentConfig: {{ .Release.Name }}-{{ .Values.version }}
      name: {{ .Release.Name }}
    spec:
      containers:
      - env: []
{{ if .Values.externalImage.enabled }}
        image: {{ .Release.Name }}
{{ else }}
        image: {{ .Values.externalImage.registry }}/{{ .Values.externalImage.imageName }}:{{ .Values.externalImage.tag }}
{{ end }}
        imagePullPolicy: Always
        name: {{ .Release.Name }}
        ports:
        - containerPort: 8778
          name: jolokia
          protocol: TCP
        - containerPort: 8080
          name: http
          protocol: TCP
      terminationGracePeriodSeconds: 75
{{ if .Values.isOCP }}
  triggers:
  - imageChangeParams:
      automatic: true
      containerNames:
      - {{ .Release.Name }}
      from:
        kind: ImageStreamTag
        name: {{ .Release.Name }}:{{ .Values.version }}
    type: ImageChange
  - type: ConfigChange
{{ end }}
