apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-certs
  labels:
    app: {{ .Release.Name }}
    chart: {{ Charts.Name }}
    release: {{ .Release.Name | quote }}
type: Opaque
data:
{{- if .Values.ssl.generateTLS }}
  {{- $ca := genCA "default-ca" .Values.ssl.ca-lifespan }}
  {{- $cn := default {{ .Release.Name }}-svc.{{ .Release.Namespace }}.svc.cluster.local .Values.ssl.defaultCN }}
  {{- $server := genSignedCert $cn ( default nil .Values.ssl.defaultIPList ) ( default nil .Values.ssl.defaultSANList ) .Values.ssl.tls-lifespan $ca }}
  tls.crt: {{ $server.Cert | b64enc }}
  tls.key: {{ $server.Key | b64enc }}
{{- else }}
  tls.crt: {{ .Values.ssl.defaultCert }}
  tls.key: {{ .Values.ssl.defaultKey }}
{{- end }}