apiVersion: v1
kind: Service
metadata:
  annotations:
    description: The application's http port.
  labels:
    app: {{ .Release.Name }}
    version: {{ .Chart.AppVersion | quote }}
  name: "{{ .Release.Name }}-svc"
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: {{ .Release.Name }}
