apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.jenkins.phase }}-{{ .Values.jenkins.name }}-{{ .Values.jenkins.version }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.jenkins.phase }}-{{ Values.jenkins.name }}
  strategy:
    type: Recreate
  template:
    metadata:
      label:
        app: {{ .Values.jenkins.phase }}-{{ .Values.jenkins.name }}
    spec:
      containers:
      - image: docker.io.jenkins/jenkins:lts-jdk11
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 2
          httpGet:
            path: /login
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 420
          periodSeconds: 360
          successThreshold: 1
          timeoutSeconds: 240
        name: jenkins
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /login
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 240
        resources:
          {{ toYaml .Values.jenkins.resources | indent 4 }}
        securityContext:
          capabilities: {}
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/jenkins
          name: jenkins-data
        - mountPath: /etc/pki/ca-trust/source/anchors
          name: jenkins-trusted-ca-bundle
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: jenkins
      serviceAccountName: jenkins
      terminationGracePeriodSeconds: 30
      volumes:
      - name: jenkins-data
        {{- if .Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ .Values.jenkins.phase }}-{{ .Values.jenkins.name }}-pvc
        {{- else }}
        emptyDir: {}
        {{- end }}
      - configMap:
          defaultMode: 420
          name: {{ .Values.jenkins.phase }}-{{ .Values.jenkins.name }}-trusted-ca-bundle
          optional: true
        name: jenkins-trusted-ca-bundle
  triggers:
  - imageChangeParams:
      automatic: true
      containerNames:
      - jenkins
      from:
        kind: ImageStreamTag
        name: jenkins:2
        namespace: openshift
      lastTriggeredImage: ""
    type: ImageChange
  - type: ConfigChange
