useDeploymentConfig: false
name: openjdk-11-app
image:
  isExternal: true
  registry: docker.io
  name: jenkins/jenkins
  tag: latest
  pullPolicy: Always

replicaCount: 1
deployStrategy: Recreate
terminationGracePeriodSeconds: 30

#env: 
#  - name: TZ
#    value: "Asia/Seoul"

serviceAccount:
  change: false
#  name: "jenkins"

ports:
  - containerPort: 8080
    name: http
    protocol: TCP
          
service:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      name: http

persistence:
  - volumeName: tmp-hostpath
    mountPath: /tmp/hostPath
    volumeSpec:
      hostPath:
        path: /tmp
  - volumeName: tmp-emptydir
    mountPath: /tmp/emptyDir
    volumeSpec:
      emptyDir: {}
#    pvcSpec:
#      storageClass: manual
#      annotations: {}
#      accessModes:
#        - ReadWriteOnce
#      size: 8Gi

resources: 
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

probes:
  livenessProbeEnabled: false
  readinessProbeEnabled: false
#  livenessProbe:
#    failureThreshold: 2
#    httpGet:
#      path: /login
#      port: 8080
#      scheme: HTTP
#    initialDelaySeconds: 420
#    periodSeconds: 360
#    successThreshold: 1
#    timeoutSeconds: 240
#  readinessProbe:
#    failureThreshold: 3
#    httpGet:
#      path: /login
#      port: 8080
#      scheme: HTTP
#    initialDelaySeconds: 3
#    periodSeconds: 10
#    successThreshold: 1
#    timeoutSeconds: 240