apiVersion: v2
name: jenkins
description: Jenkins is an open source automation server which enables developers to build, test, and deploy their software using pipelines. This chart allows the installation of th Jenkins on OpenShift image and enables a various set of plugins to improve cloud experience with Jenkins.
type: application
version: 0.0.3
appVersion: "1.16.0"
keywords:
- ci/cd
- pipeline
- jenkins
