{{ if .Values.isOCP }}
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
{{ else }}
apiVersion: apps/v1
kind: Deployment
{{ end }}
metadata:
  labels:
    application: {{ .Release.Name }}
    version: {{ .Values.version }}
  name: {{ .Release.Name }}-{{ .Values.version }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      deploymentConfig: {{ .Release.Name }}-{{ .Values.version }} 
  strategy:
    type: {{ .Values.deployStrategy }}
  template:
    metadata:
      labels:
        application: {{ .Release.Name }}
        version: {{ .Values.version }}
        deploymentConfig: {{ .Release.Name }}-{{ .Values.version }}
      name: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ .Release.Name }}  
{{ if .Values.env }}        
        env:
{{ toYaml .Values.env | indent 8 }}
{{ end }}
{{ if .Values.externalImage.enabled }}
        image: {{ .Values.externalImage.registry }}/{{ .Values.externalImage.imageName }}:{{ .Values.externalImage.tag }}
{{ else }}
        image: {{ .Release.Name }}
{{ end }}
        imagePullPolicy: Always
{{ if .Values.resources }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
{{ end }}
        ports:
{{ toYaml .Values.ports | indent 8 }}
      terminationGracePeriodSeconds: 75
{{ if .Values.isOCP }}
  triggers:
  - imageChangeParams:
      automatic: true
      containerNames:
      - {{ .Release.Name }}
      from:
        kind: ImageStreamTag
        name: {{ .Release.Name }}:{{ .Values.version }}
    type: ImageChange
  - type: ConfigChange
{{ end }}
