{{- if .Values.isOCP }}
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
{{- else }}
apiVersion: apps/v1
kind: Deployment
{{- end }}
metadata:
  labels:
    app: {{ .Release.Name }}
    version: {{ .Chart.AppVersion | quote }}
  name: "{{ .Release.Name }}-{{ .Chart.AppVersion }}"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      deploymentConfig: {{ .Release.Name }}-{{ .Chart.AppVersion }} 
  strategy:
    type: {{ .Values.deployStrategy }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        version: {{ .Chart.AppVersion }}
        deploymentConfig: {{ .Release.Name }}-{{ .Chart.AppVersion }}
      name: {{ .Release.Name }}
    spec:
{{- if .Values.serviceAccount.change }}
      serviceAccountName: {{ .Values.serviceAccount.name }}
{{- else }}
      serviceAccountName: default
{{- end}}
      containers:
      - name: {{ .Release.Name }}  
{{- if .Values.env }}        
        env:
{{ toYaml .Values.env | indent 8 }}
{{- end }}
{{- if .Values.image.externalEnabled }}
        image: {{ .Values.image.registry }}/{{ .Values.image.name }}:{{ .Values.image.tag }}
{{- else }}
        image: {{ .Release.Name }}
{{- end }}
        imagePullPolicy: Always
{{- if .Values.resources }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
{{- end }}
        ports:
{{ toYaml .Values.ports | indent 8 }}
      terminationGracePeriodSeconds: 75
{{- if and (.Values.isOCP) (eq .Values.image.externalEnabled "false") }}
  triggers:
  - imageChangeParams:
      automatic: true
      containerNames:
      - {{ .Release.Name }}
      from:
        kind: ImageStreamTag
        name: {{ .Release.Name }}:{{ .Chart.AppVersion }}
    type: ImageChange
  - type: ConfigChange
{{- end }}
